// celebs-angular/src/app/components/celeb-toolbar/celeb-toolbar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-celeb-toolbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './celeb-toolbar.component.html',
  styleUrls: ['./celeb-toolbar.component.css']
})
export class CelebToolbarComponent {
  @Input() viewMode: 'grid' | 'list' = 'grid';
  @Output() toggleView = new EventEmitter<void>();
  @Output() reset = new EventEmitter<void>();

  onToggleView(): void {
    this.toggleView.emit();
  }

  onReset(): void {
    this.reset.emit();
  }
}

<div class="flex justify-between items-center mb-6">
  <button
    (click)="onReset()"
    class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition"
  >
    Reset
  </button>
  <button
    (click)="onToggleView()"
    class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition ml-4"
  >
    {{viewMode === 'grid' ? 'Show as List' : 'Show as Grid'}}
  </button>
</div>

// celebs-react/src/components/CelebToolbar.tsx
type Props = {
  viewMode: 'grid' | 'list';
  onToggleView: () => void;
  onReset: () => void;
};

export default function CelebToolbar({ viewMode, onToggleView, onReset }: Props) {
  return (
    <div className="flex justify-between items-center mb-6">
      <button
        onClick={onReset}
        className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition"
      >
        Reset
      </button>
      <button
        onClick={onToggleView}
        className="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition ml-4"
      >
        {viewMode === 'grid' ? 'Show as List' : 'Show as Grid'}
      </button>
    </div>
  );
}
